### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by TylorS** [TylorS/typed-fp#10]
We only have a few examples so far, it'd be great to expand into more FE/BE examples. 

If anyone has some ideas that'd be helpful for them to learn, please add your thoughts to this thread!

**Comment by TylorS** [comment]
There are now a Counters app which demonstrates how to use Ref to create many sibling components with isolated state.

There is also now an implementation of TodoMVC which also demonstrates using Ref, Env, and ReaderStream.

**Comment by TylorS** [comment]
I somewhat simplified the Counters app to show a single counter app in isolation

**Comment by ahrjarrett** [comment]
What kind of example(s) do you feel would be most helpful? I'd enjoy the learning experience of trying to build something if you're able to give me feedback when you see a better implementation / choice of ADT, for example.

**Comment by TylorS** [comment]
Hey @ahrjarrett I'm pretty open to example ideas that works help with learning the library, I'll spend some time thinking of some too

**Comment by ahrjarrett** [comment]
awesome -- sorry I've been out of pocket, I'm working on a big refactor at work and haven't had time to do much else

I've got a break this morning so I'm planning to read the source for Stream

**Comment by Frikki** [comment]
I am thinking 🤔
