### ISSUE TITLE
Licensing and `LICENSE` file

### ISSUE THREAD

**Issue by 0x706b** [TylorS/typed-fp#11]
Hello! First of all I would like to say, thank you for this library; there are many great concepts here. I'm wondering though, would you be amenable to adding a `LICENSE` file to this repo? The `package.json` has `MIT` in the license field, but there is no `LICENSE` file in the base of this repo. I would like to make sure this library is safe for me to use.

All the best!

**Comment by TylorS** [comment]
Hey @0x706b thanks for opening the issue! I'm totally fine with adding the license file, it is my intent to keep @typed/fp under the MIT license for at least the foreseeable future

**Comment by 0x706b** [comment]
@TylorS Fantastic! I submitted a PR adding the license file with the MIT license
