### ISSUE TITLE
realworld example doesn't start

### ISSUE THREAD

**Issue by guillempuche** [TylorS/typed-fp#62]
In `development` branch of `realworld` example, and after `pnpm i` & `docker up`, running `pmpm start` throws this:

```sh
pnpm start

> @typed/example-realworld@0.0.0 start /Users/guillem/programacio/codi/cites/databases/effect-typed/examples/realworld
> vite --config ./vite.config.mts serve --force src

failed to load config from /Users/guillem/programacio/codi/cites/databases/effect-typed/examples/realworld/vite.config.mts
error when starting dev server:
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@typed/vite-plugin' imported from /Users/guillem/programacio/codi/cites/databases/effect-typed/examples/realworld/vite.config.mts.timestamp-1716481104804-ecd30aef0c94.mjs
    at new NodeError (node:internal/errors:406:5)
    at packageResolve (node:internal/modules/esm/resolve:789:9)
    at moduleResolve (node:internal/modules/esm/resolve:838:20)
    at defaultResolve (node:internal/modules/esm/resolve:1043:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:383:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:352:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:228:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:85:39)
    at link (node:internal/modules/esm/module_job:84:36)
 ELIFECYCLE  Command failed with exit code 1.
 ```

**Comment by guillempuche** [comment]
Just need to run `pnpm build` from the root directory (don't need to install the packages in the root directory). Go to the example directory again, and run `pnpm start`

**Comment by TylorS** [comment]
Hey @guillempuche Thanks for the issue, and sorry for the confusion! As you pointed out, my instructions are lacking the `pnpm install` and `pnpm build` steps at the root of the repository before being able to run the example. This is due to using `workspace:*` links, and needing local builds of the code to function. 

I'll update the docs in the meantime, and I'll work on getting those `workspace:*` links replaced with npm references now that everything is published to NPM.

**Comment by TylorS** [comment]
Docs have been updated, lemma know if they're not clear or representation of what you actually needed to do - https://github.com/TylorS/typed/blob/development/examples/realworld/README.md#getting-started

**Comment by guillempuche** [comment]
I installed the packages only in the example folder, not from the root, as I didn't want the whole suite of packages.
